# Generated by Django 3.1.3 on 2021-02-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0003_auto_20210201_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=40),
        ),
    ]
